version: "3.0"
services:
  pycharm:
    build:
      context: .
      dockerfile: docker/pycharm/Dockerfile
      args:
        username: $USER
        userid: $UID
    command: $HOME/pycharm/bin/pycharm.sh
    user: $USER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
      - .:/code:z
      - $PYCHARM_DIR:$HOME/pycharm:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.cache:$HOME/.cache:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.java:$HOME/.java:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.PyCharm:$HOME/.PyCharm:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.PyCharm2018.1:$HOME/.PyCharm2018.1:z
    links:
      - db
      - web
    env_file:
      - .env.default
      - .env
      - .env.pycharm
    logging:
      driver: "json-file"
      options:
        max-size: 10k
