version: "3.0"
services:
  pycharm:
    build:
      context: .
      dockerfile: docker/pycharm/Dockerfile
      args:
        username: $DEVUSER
        userid: $UID
    command: /home/$DEVUSER/pycharm/bin/pycharm.sh
    user: $DEVUSER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
      - .:/code:z
      - $PYCHARM_DIR:/home/$DEVUSER/pycharm:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.cache:/home/$DEVUSER/.cache:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.java:/home/$DEVUSER/.java:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.PyCharm:/home/$DEVUSER/.PyCharm:z
      - ~/pycharm-docker/$COMPOSE_PROJECT_NAME/.PyCharm2018.1:/home/$DEVUSER/.PyCharm2018.1:z
    links:
      - db
      - web
    env_file:
      - .env.default
      - .env
      - .env.pycharm
    logging:
      driver: "json-file"
      options:
        max-size: 10k
